# Generated by Django 5.2 on 2025-04-14 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patienttodocrelation_patients_patientnaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttodocrelation',
            name='patients',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='patients.patientmodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PatientNaming',
        ),
    ]
