# Generated by Django 5.2 on 2025-04-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patients', '0005_patienttodocrelation_patients_delete_patientnaming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentModel',
            new_name='DoctorSelectionModel',
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='attending_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctormodel'),
        ),
        migrations.DeleteModel(
            name='PatienttoDocRelation',
        ),
    ]
