# Generated by Django 5.2 on 2025-04-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_departmentmodel_doctorselectionmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorSelectionModel',
        ),
    ]
