# Generated by Django 5.2 on 2025-04-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursemodel',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurses.departmentmodel'),
        ),
    ]
