# Generated by Django 5.2 on 2025-04-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_alter_nursemodel_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursemodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
